# Generated by Django 2.0.7 on 2018-07-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_squashed_0003_timeframe_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='url',
            field=models.CharField(default='', max_length=120),
        ),
    ]
