# Generated by Django 2.0.7 on 2018-07-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20180727_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeframe',
            name='minutes',
            field=models.IntegerField(default=1),
        ),
    ]
