# Generated by Django 2.0.7 on 2018-08-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20180731_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairdata',
            name='volume',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
    ]
