# Generated by Django 2.0.7 on 2018-08-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20180809_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairdata',
            name='volume',
            field=models.DecimalField(decimal_places=7, max_digits=12),
        ),
    ]
