# Generated by Django 2.0.7 on 2018-08-15 15:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_auto_20180809_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairdata',
            name='open_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
